In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#display all column
pd.set_option('display.max_columns', None)

In [ ]:
#Reading the dataset
df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/glassdoor_reviews.csv')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 838566 entries, 0 to 838565
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   firm                 838566 non-null  object
 1   date_review          838566 non-null  object
 2   job_title            838566 non-null  object
 3   current              838566 non-null  object
 4   location             541223 non-null  object
 5   overall_rating       838566 non-null  int64
 6   work_life_balance    688672 non-null  float64
 7   culture_values       647193 non-null  float64
 8   diversity_inclusion  136066 non-null  float64
 9   career_opp           691065 non-null  float64
 10  comp_benefits        688484 non-null  float64
 11  senior_mgmt          682690 non-null  float64
 12  recommend            838566 non-null  object
 13  ceo_approv           838566 non-null  object
 14  outlook              838566 non-null  object
 15  headline             835976 non-null  object
 16  pros                 838564 non-null  object
 17  cons                 838553 non-null  object
dtypes: float64(6), int64(1), object(11)
memory usage: 115.2+ MB

In [ ]:
df1.firm.value_counts()

firm
IBM                         60436
McDonald-s                  49450
Deloitte                    46995
EY                          34050
PwC                         33227
                            ...
Health-Protection-Agency        4
i-Net-Solution                  4
The-Survey-Association          3
NPSA                            2
UKCIL                           1
Name: count, Length: 428, dtype: int64

In [ ]:
df2 = pd.DataFrame(df1.firm.value_counts())
df2.head(10)

            count
firm
IBM         60436
McDonald-s  49450
Deloitte    46995
EY          34050
PwC         33227
Oracle      31941
Microsoft   26675
J-P-Morgan  25814
KPMG        24815
Apple       20797

In [ ]:
df1.isnull().sum()/len(df1)*100

firm                    0.000000
date_review             0.000000
job_title               0.000000
current                 0.000000
location               35.458509
overall_rating          0.000000
work_life_balance      17.875039
culture_values         22.821459
diversity_inclusion    83.773967
career_opp             17.589671
comp_benefits          17.897458
senior_mgmt            18.588400
recommend               0.000000
ceo_approv              0.000000
outlook                 0.000000
headline                0.308861
pros                    0.000239
cons                    0.001550
dtype: float64

In [ ]:
df3 = df1[df1['firm'] == 'IBM']
df3.head()

,firm,date_review,job_title,current,location,overall_rating,work_life_balance,culture_values,diversity_inclusion,career_opp,comp_benefits,senior_mgmt,recommend,ceo_approv,outlook,headline,pros,cons
341409,IBM,2008-05-30,IT Architect,Current Employee,"Essex Junction, VT",4,5.0,NaN,NaN,4.0,4.0,3.0,v,v,o,The grass is probably less brown at IBM than a...,Availability of information resources to help ...,Politically correct (PC) version of diversity ...
341410,IBM,2008-06-01,Senior Software Engineer,Current Employee,"Poughkeepsie, NY",5,5.0,NaN,NaN,5.0,3.0,5.0,v,v,o,IBM - Still The Best Company To Work For Year ...,IBM is a large company with a lot of great peo...,"It is a large company, and this isn't for ever..."
341411,IBM,2008-06-03,IT Specialist,Current Employee,"New York, NY",5,4.0,NaN,NaN,5.0,4.0,4.0,v,v,o,IBM is a very good place to work,IBM has a very structured approach to personal...,The main negative about working for IBM is tie...
341412,IBM,2008-06-03,Sales,Current Employee,"Toronto, ON",5,5.0,NaN,NaN,4.0,3.0,5.0,v,x,o,The world is our oyster...,Quality of the people I work with and the rewa...,The breadth of the value we can provide our cu...
341413,IBM,2008-06-05,Education Consultant,Current Employee,"Atlanta, GA",3,2.0,NaN,NaN,3.0,4.0,2.0,o,r,o,A Good Company with a Few Tragic Flaws,IBM is the largest education provider in the i...,Excessive hours. Mandatory travel. Persons who...

In [ ]:
df3['overall_rating'].value_counts()/len(df3)*100 #IBM

overall_rating
4    34.074062
3    28.271229
5    20.630088
2    10.872659
1     6.151962
Name: count, dtype: float64

In [ ]:
#IBM, Apple), food (McDonald's), and consulting (Deloitte).

In [ ]:
df5 = df1[df1['firm'] == 'McDonald-s' ]
df5.head()

,firm,date_review,job_title,current,location,overall_rating,work_life_balance,culture_values,diversity_inclusion,career_opp,comp_benefits,senior_mgmt,recommend,ceo_approv,outlook,headline,pros,cons
503785,McDonald-s,2008-09-18,Store Manager,Current Employee,"Columbus, OH",4,3.0,NaN,NaN,4.0,3.0,4.0,o,v,o,Store Manager for McDonalds,"The vacation time is good. After five years, ...",Sometimes certain locations can be much worse ...
503786,McDonald-s,2008-09-19,"Cook, Fast Food",Current Employee,"Mercer, PA",1,1.0,NaN,NaN,1.0,1.0,1.0,x,x,o,Its better than starving,"If you need the moeny, it is better than selli...","Greasy skin, bad pay, terrible bosses, moronic..."
503787,McDonald-s,2008-09-19,Crew Trainer,Current Employee,"Green Bay, WI",4,2.0,NaN,NaN,3.0,3.0,3.0,v,v,o,Crew member at McDonalds,It was a great opportunity to work at while st...,Just some of the people you worked with. You ...
503788,McDonald-s,2008-09-25,Cashier,Current Employee,NaN,2,3.0,NaN,NaN,2.0,3.0,2.0,x,r,o,Only looks good on your resume,Conveniece and a good work experience. Usually...,Overworked compared to other kinds of food ret...
503789,McDonald-s,2008-09-25,Head Office,Current Employee,"Toronto, ON",4,2.0,NaN,NaN,4.0,2.0,4.0,v,v,o,McDonald's is a good place to work with a lot ...,Team work is key. Plan to Win is a great stra...,Salary and benefits are just average. Workloa...

In [ ]:
df5['overall_rating'].value_counts()/len(df5)*100 # Mcdonalds

overall_rating
3    31.456016
4    25.306370
5    20.038423
2    12.841254
1    10.357937
Name: count, dtype: float64

In [ ]:
df6 = df1[df1['firm'] == 'Apple' ]
df6.head()
df6['overall_rating'].value_counts()/len(df6)*100

overall_rating
5    41.996442
4    33.278838
3    15.910949
2     5.197865
1     3.615906
Name: count, dtype: float64

In [ ]:
df7 = df1[df1['firm'] == 'Deloitte' ]
df7.head()
df7['overall_rating'].value_counts()/len(df7)*100

overall_rating
4    40.832003
5    25.926162
3    22.617300
2     6.560272
1     4.064262
Name: count, dtype: float64

In [ ]:
''' EY	34050
PwC	33227
Oracle	31941
Microsoft	26675
J-P-Morgan	25814
KPMG	24815 '''

' EY\t34050\nPwC\t33227\nOracle\t31941\nMicrosoft\t26675\nJ-P-Morgan\t25814\nKPMG\t24815 '

In [ ]:
df8 = df1[df1['firm'] == 'EY' ]
df8.head()
df8['overall_rating'].value_counts()/len(df8)*100

overall_rating
4    41.089574
3    24.464023
5    23.665198
2     6.716593
1     4.064611
Name: count, dtype: float64

In [ ]:
df9 = df1[df1['firm'] == 'PwC' ]
df9.head()
df9['overall_rating'].value_counts()/len(df9)*100

overall_rating
4    40.867367
5    24.549312
3    23.881181
2     6.545881
1     4.156258
Name: count, dtype: float64

In [ ]:
df10 = df1[df1['firm'] == 'Oracle' ]
df10.head()
df10['overall_rating'].value_counts()/len(df10)*100

overall_rating
4    35.333897
3    31.674024
5    16.383332
2    10.832472
1     5.776275
Name: count, dtype: float64

In [ ]:
df11 = df1[df1['firm'] == 'Microsoft' ]
df11['overall_rating'].value_counts()/len(df11)*100

overall_rating
4    36.903468
5    36.371134
3    17.668229
2     5.866917
1     3.190253
Name: count, dtype: float64

In [ ]:
df12 = df1[df1['firm'] == 'J-P-Morgan' ]
df12['overall_rating'].value_counts()/len(df12)*100

overall_rating
4    36.518943
5    26.524367
3    23.770047
2     8.049895
1     5.136748
Name: count, dtype: float64

In [ ]:
df13 = df1[df1['firm'] == 'KPMG' ]
df13['overall_rating'].value_counts()/len(df13)*100

overall_rating
4    40.556115
3    26.165626
5    21.212976
2     7.539794
1     4.525489
Name: count, dtype: float64

In [ ]:
#IBM, MCD, #JP MORGAN, #ORACLE

In [ ]:
df1.head()

,firm,date_review,job_title,current,location,overall_rating,work_life_balance,culture_values,diversity_inclusion,career_opp,comp_benefits,senior_mgmt,recommend,ceo_approv,outlook,headline,pros,cons
0,AFH-Wealth-Management,2015-04-05,,Current Employee,NaN,2,4.0,3.0,NaN,2.0,3.0,3.0,x,o,r,"Young colleagues, poor micro management",Very friendly and welcoming to new staff. Easy...,"Poor salaries, poor training and communication."
1,AFH-Wealth-Management,2015-12-11,Office Administrator,"Current Employee, more than 1 year","Bromsgrove, England, England",2,3.0,1.0,NaN,2.0,1.0,4.0,x,o,r,"Excellent staff, poor salary","Friendly, helpful and hard-working colleagues",Poor salary which doesn't improve much with pr...
2,AFH-Wealth-Management,2016-01-28,Office Administrator,"Current Employee, less than 1 year","Bromsgrove, England, England",1,1.0,1.0,NaN,1.0,1.0,1.0,x,o,x,"Low salary, bad micromanagement",Easy to get the job even without experience in...,"Very low salary, poor working conditions, very..."
3,AFH-Wealth-Management,2016-04-16,,Current Employee,NaN,5,2.0,3.0,NaN,2.0,2.0,3.0,x,o,r,Over promised under delivered,Nice staff to work with,No career progression and salary is poor
4,AFH-Wealth-Management,2016-04-23,Office Administrator,"Current Employee, more than 1 year","Bromsgrove, England, England",1,2.0,1.0,NaN,2.0,1.0,1.0,x,o,x,client reporting admin,"Easy to get the job, Nice colleagues.","Abysmal pay, around minimum wage. No actual tr..."

In [ ]:
# df12,df10,df5,df3

In [ ]:
print(df3.isnull().sum()/len(df3)*100) #IBM
#print(df5.isnull().sum()/len(df5)*100)
#print(df10.isnull().sum()/len(df10)*100)
#print(df12.isnull().sum()/len(df12)*100)
#

firm                    0.000000
date_review             0.000000
job_title               0.000000
current                 0.000000
location               36.200278
overall_rating          0.000000
work_life_balance      14.842147
culture_values         23.368522
diversity_inclusion    86.279701
career_opp             14.704812
comp_benefits          14.855384
senior_mgmt            15.575154
recommend               0.000000
ceo_approv              0.000000
outlook                 0.000000
headline                0.311073
pros                    0.000000
cons                    0.000000
dtype: float64

In [ ]:
print(df5.isnull().sum()/len(df5)*100) #Mcdonalds

firm                    0.000000
date_review             0.000000
job_title               0.000000
current                 0.000000
location               43.330637
overall_rating          0.000000
work_life_balance      29.516684
culture_values         31.856421
diversity_inclusion    80.972700
career_opp             28.463094
comp_benefits          29.468150
senior_mgmt            30.709808
recommend               0.000000
ceo_approv              0.000000
outlook                 0.000000
headline                0.323559
pros                    0.000000
cons                    0.000000
dtype: float64

In [ ]:
print(df10.isnull().sum()/len(df10)*100) #Oracle

firm                    0.000000
date_review             0.000000
job_title               0.000000
current                 0.000000
location               36.382706
overall_rating          0.000000
work_life_balance      15.074669
culture_values         21.530322
diversity_inclusion    87.035472
career_opp             15.084061
comp_benefits          15.018315
senior_mgmt            15.647600
recommend               0.000000
ceo_approv              0.000000
outlook                 0.000000
headline                0.269246
pros                    0.000000
cons                    0.000000
dtype: float64

In [ ]:
print(df12.isnull().sum()/len(df12)*100) #JPMorgan

firm                    0.000000
date_review             0.000000
job_title               0.000000
current                 0.000000
location               35.368405
overall_rating          0.000000
work_life_balance      17.874022
culture_values         24.021849
diversity_inclusion    84.806694
career_opp             17.722941
comp_benefits          17.812040
senior_mgmt            18.493841
recommend               0.000000
ceo_approv              0.000000
outlook                 0.000000
headline                0.402882
pros                    0.000000
cons                    0.000000
dtype: float64

In [ ]:
#exporting data to drive
df12.to_csv('/content/drive/MyDrive/Colab Notebooks/Data/glassdoor_reviewsdf12.csv')

In [ ]:
#exporting data to drive
df10.to_csv('/content/drive/MyDrive/Colab Notebooks/Data/glassdoor_reviewsdf10.csv')

In [ ]:
#exporting data to drive
df5.to_csv('/content/drive/MyDrive/Colab Notebooks/Data/glassdoor_reviewsdf5.csv')

In [ ]:
#exporting data to drive
df3.to_csv('/content/drive/MyDrive/Colab Notebooks/Data/glassdoor_reviewsdf3.csv')

In [ ]:
L1 = ['firm',
    'overall_rating',
    'pros',
    'cons',
    'headline',
    'recommend',
    'ceo_approv',
    'outlook',
    'current',
    'job_title',
    'date_review',
    'work_life_balance',
    'culture_values',
    'career_opp',
    'comp_benefits',
    'senior_mgmt'
]

In [ ]:
df5= df5[L1]
df5.head()

,firm,overall_rating,pros,cons,headline,recommend,ceo_approv,outlook,current,job_title,date_review,work_life_balance,culture_values,career_opp,comp_benefits,senior_mgmt
503785,McDonald-s,4,"The vacation time is good. After five years, ...",Sometimes certain locations can be much worse ...,Store Manager for McDonalds,o,v,o,Current Employee,Store Manager,2008-09-18,3.0,NaN,4.0,3.0,4.0
503786,McDonald-s,1,"If you need the moeny, it is better than selli...","Greasy skin, bad pay, terrible bosses, moronic...",Its better than starving,x,x,o,Current Employee,"Cook, Fast Food",2008-09-19,1.0,NaN,1.0,1.0,1.0
503787,McDonald-s,4,It was a great opportunity to work at while st...,Just some of the people you worked with. You ...,Crew member at McDonalds,v,v,o,Current Employee,Crew Trainer,2008-09-19,2.0,NaN,3.0,3.0,3.0
503788,McDonald-s,2,Conveniece and a good work experience. Usually...,Overworked compared to other kinds of food ret...,Only looks good on your resume,x,r,o,Current Employee,Cashier,2008-09-25,3.0,NaN,2.0,3.0,2.0
503789,McDonald-s,4,Team work is key. Plan to Win is a great stra...,Salary and benefits are just average. Workloa...,McDonald's is a good place to work with a lot ...,v,v,o,Current Employee,Head Office,2008-09-25,2.0,NaN,4.0,2.0,4.0

In [ ]:
df3= df3[L1]
df3.head()

,firm,overall_rating,pros,cons,headline,recommend,ceo_approv,outlook,current,job_title,date_review,work_life_balance,culture_values,career_opp,comp_benefits,senior_mgmt
341409,IBM,4,Availability of information resources to help ...,Politically correct (PC) version of diversity ...,The grass is probably less brown at IBM than a...,v,v,o,Current Employee,IT Architect,2008-05-30,5.0,NaN,4.0,4.0,3.0
341410,IBM,5,IBM is a large company with a lot of great peo...,"It is a large company, and this isn't for ever...",IBM - Still The Best Company To Work For Year ...,v,v,o,Current Employee,Senior Software Engineer,2008-06-01,5.0,NaN,5.0,3.0,5.0
341411,IBM,5,IBM has a very structured approach to personal...,The main negative about working for IBM is tie...,IBM is a very good place to work,v,v,o,Current Employee,IT Specialist,2008-06-03,4.0,NaN,5.0,4.0,4.0
341412,IBM,5,Quality of the people I work with and the rewa...,The breadth of the value we can provide our cu...,The world is our oyster...,v,x,o,Current Employee,Sales,2008-06-03,5.0,NaN,4.0,3.0,5.0
341413,IBM,3,IBM is the largest education provider in the i...,Excessive hours. Mandatory travel. Persons who...,A Good Company with a Few Tragic Flaws,o,r,o,Current Employee,Education Consultant,2008-06-05,2.0,NaN,3.0,4.0,2.0

In [ ]:
df10= df10[L1]
df10.head()

,firm,overall_rating,pros,cons,headline,recommend,ceo_approv,outlook,current,job_title,date_review,work_life_balance,culture_values,career_opp,comp_benefits,senior_mgmt
615202,Oracle,3,Incredible opportunity for growth within compa...,There are too few employees. Often we have to ...,"Challenging, but many opportunity to learn and...",x,r,o,Current Employee,QA Software Engineer,2008-03-18,4.0,NaN,3.0,3.0,4.0
615203,Oracle,4,One of the best things about working here is t...,The fact that we have layoffs about every 2 ye...,It is a job that pays the bills.,v,v,o,Current Employee,Senior Applications Engineer,2008-04-08,4.0,NaN,4.0,3.0,5.0
615204,Oracle,3,Benefits - one of the most comprehensive benef...,Too big at times - you have to deal with a num...,"Oracle - a good place to work, with some room ...",v,v,o,Current Employee,Senior Director,2008-04-23,3.0,NaN,3.0,4.0,2.0
615205,Oracle,4,Flexible work arrangements. Equitable compens...,I was part of the PeopleSoft takeover. Oracle...,It's ok to work at Oracle.,v,r,o,Current Employee,Principal Support Engineer,2008-04-24,5.0,NaN,4.0,4.0,3.0
615206,Oracle,1,Oracle allows you to work from anywhere as lon...,There are many! slave labor comes to mind!,Stay away from Oracle!,x,x,o,Current Employee,Product Management Director,2008-05-04,3.0,NaN,1.0,1.0,1.0

In [ ]:
df12= df12[L1]
df12.head()

,firm,overall_rating,pros,cons,headline,recommend,ceo_approv,outlook,current,job_title,date_review,work_life_balance,culture_values,career_opp,comp_benefits,senior_mgmt
408410,J-P-Morgan,4,Good compensation package and some of the smar...,"Very long hours, and at times when work just p...","Good place to work for, very good pay and resp...",v,v,o,Former Employee,Analyst,2008-05-05,3.0,NaN,5.0,4.0,5.0
408411,J-P-Morgan,5,It is a wonderful place to network and meet pe...,"At times, working for a big company like this,...",JPMorgan is one of the best places for people ...,v,v,o,Former Employee,Investment Banking Analyst,2008-05-07,4.0,NaN,5.0,3.0,3.0
408412,J-P-Morgan,4,The Benefits at Chase are top notch. The work...,Some of the downsides are probably working for...,Satisfied Employee Working for Chase,v,v,o,Current Employee,Risk Operations Analyst,2008-05-07,3.0,NaN,4.0,4.0,3.0
408413,J-P-Morgan,4,"The Private Bank, under Asset Management has d...","It is a large scale company, and while this cr...",JPMorgan is all about the people - educating t...,v,v,o,Former Employee,Associate Project Manager,2008-05-08,4.0,NaN,4.0,3.0,4.0
408414,J-P-Morgan,2,Leader in the financial industry\r\nGlobal rea...,Senior management incapable of managing around...,"Jamie has point, but who's got his back?",x,v,o,Current Employee,Vice President,2008-05-10,3.0,NaN,2.0,3.0,1.0

In [ ]:
print(df3.isnull().sum()) #IBM


print(df5.isnull().sum()) #Mcdonalds


print(df10.isnull().sum()) #Oracle


print(df12.isnull().sum()) #JPMorgan

firm                     0
overall_rating           0
pros                     0
cons                     0
headline               188
recommend                0
ceo_approv               0
outlook                  0
current                  0
job_title                0
date_review              0
work_life_balance     8970
culture_values       14123
career_opp            8887
comp_benefits         8978
senior_mgmt           9413
dtype: int64
firm                     0
overall_rating           0
pros                     0
cons                     0
headline               160
recommend                0
ceo_approv               0
outlook                  0
current                  0
job_title                0
date_review              0
work_life_balance    14596
culture_values       15753
career_opp           14075
comp_benefits        14572
senior_mgmt          15186
dtype: int64
firm                    0
overall_rating          0
pros                    0
cons                    0
headline               86
recommend               0
ceo_approv              0
outlook                 0
current                 0
job_title               0
date_review             0
work_life_balance    4815
culture_values       6877
career_opp           4818
comp_benefits        4797
senior_mgmt          4998
dtype: int64
firm                    0
overall_rating          0
pros                    0
cons                    0
headline              104
recommend               0
ceo_approv              0
outlook                 0
current                 0
job_title               0
date_review             0
work_life_balance    4614
culture_values       6201
career_opp           4575
comp_benefits        4598
senior_mgmt          4774
dtype: int64

In [ ]:
for col in ['work_life_balance', 'culture_values', 'career_opp', 'comp_benefits', 'senior_mgmt']:
    df3[f'{col}_missing'] = df3[col].isna().astype(int)
    df3[col].fillna(3, inplace=True)  # Neutral imputation

<ipython-input-101-ccc2bc92787b>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-101-ccc2bc92787b>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-101-ccc2bc92787b>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-101-ccc2bc92787b>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-101-ccc2bc92787b>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(3, inplace=True)  # Neutral imputation

In [ ]:
for col in ['work_life_balance', 'culture_values', 'career_opp', 'comp_benefits', 'senior_mgmt']:
    df5[f'{col}_missing'] = df5[col].isna().astype(int)
    df5[col].fillna(3, inplace=True)  # Neutral imputation

<ipython-input-102-383a4eea8dca>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-102-383a4eea8dca>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-102-383a4eea8dca>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-102-383a4eea8dca>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-102-383a4eea8dca>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5[col].fillna(3, inplace=True)  # Neutral imputation

In [ ]:
for col in ['work_life_balance', 'culture_values', 'career_opp', 'comp_benefits', 'senior_mgmt']:
    df10[f'{col}_missing'] = df10[col].isna().astype(int)
    df10[col].fillna(3, inplace=True)  # Neutral imputation

<ipython-input-103-03da17d71678>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df10[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-103-03da17d71678>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df10[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-103-03da17d71678>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df10[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-103-03da17d71678>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df10[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-103-03da17d71678>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df10[col].fillna(3, inplace=True)  # Neutral imputation

In [ ]:
for col in ['work_life_balance', 'culture_values', 'career_opp', 'comp_benefits', 'senior_mgmt']:
    df12[f'{col}_missing'] = df12[col].isna().astype(int)
    df12[col].fillna(3, inplace=True)  # Neutral imputation

<ipython-input-104-d2b80f9a03c9>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df12[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-104-d2b80f9a03c9>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df12[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-104-d2b80f9a03c9>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df12[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-104-d2b80f9a03c9>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df12[col].fillna(3, inplace=True)  # Neutral imputation
<ipython-input-104-d2b80f9a03c9>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df12[col].fillna(3, inplace=True)  # Neutral imputation

In [ ]:
# Define the code-to-label mapping
sentiment_map = {
    'v': 'Positive',
    'r': 'Mild',
    'x': 'Negative',
    'o': 'No opinion'
}

# Apply to each column
df3['recommend_label'] = df3['recommend'].map(sentiment_map)
df3['ceo_approv_label'] = df3['ceo_approv'].map(sentiment_map)
df3['outlook_label'] = df3['outlook'].map(sentiment_map)

In [ ]:
# Define the code-to-label mapping
sentiment_map = {
    'v': 'Positive',
    'r': 'Mild',
    'x': 'Negative',
    'o': 'No opinion'
}

# Apply to each column
df5['recommend_label'] = df5['recommend'].map(sentiment_map)
df5['ceo_approv_label'] = df5['ceo_approv'].map(sentiment_map)
df5['outlook_label'] = df5['outlook'].map(sentiment_map)

In [ ]:
# Define the code-to-label mapping
sentiment_map = {
    'v': 'Positive',
    'r': 'Mild',
    'x': 'Negative',
    'o': 'No opinion'
}

# Apply to each column
df10['recommend_label'] = df10['recommend'].map(sentiment_map)
df10['ceo_approv_label'] = df10['ceo_approv'].map(sentiment_map)
df10['outlook_label'] = df10['outlook'].map(sentiment_map)

In [ ]:
# Define the code-to-label mapping
sentiment_map = {
    'v': 'Positive',
    'r': 'Mild',
    'x': 'Negative',
    'o': 'No opinion'
}

# Apply to each column
df12['recommend_label'] = df12['recommend'].map(sentiment_map)
df12['ceo_approv_label'] = df12['ceo_approv'].map(sentiment_map)
df12['outlook_label'] = df12['outlook'].map(sentiment_map)

In [ ]:
df3.drop(['recommend', 'ceo_approv', 'outlook'], axis=1, inplace=True)
df5.drop(['recommend', 'ceo_approv', 'outlook'], axis=1, inplace=True)
df10.drop(['recommend', 'ceo_approv', 'outlook'], axis=1, inplace=True)
df12.drop(['recommend', 'ceo_approv', 'outlook'], axis=1, inplace=True)

In [ ]:
#exporting data to drive
df12.to_csv('/content/drive/MyDrive/Colab Notebooks/Data/glassdoor_reviewsdf12.csv')

In [ ]:
#exporting data to drive
df10.to_csv('/content/drive/MyDrive/Colab Notebooks/Data/glassdoor_reviewsdf10.csv')

In [ ]:
#exporting data to drive
df3.to_csv('/content/drive/MyDrive/Colab Notebooks/Data/glassdoor_reviewsdf3.csv')

In [ ]:
#exporting data to drive
df5.to_csv('/content/drive/MyDrive/Colab Notebooks/Data/glassdoor_reviewsdf5.csv')